app/models.py
from app import database, login_manager
from flask_login import UserMixin

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(database.Model, UserMixin):
    __tablename__ = 'users'
    id = database.Column(database.Integer, primary_key=True)
    first_name = database.Column(database.String(150), nullable=False)
    last_name = database.Column(database.String(150), nullable=False)
    date_of_birth = database.Column(database.Date, nullable=False)
    phone_number = database.Column(database.String(15), nullable=False)
    email = database.Column(database.String(150), unique=True, nullable=False)
    password = database.Column(database.String(150), nullable=False)

    def __repr__(self):
        return f'<User {self.email}>'
    

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, DateField, EmailField
from wtforms.validators import DataRequired, EqualTo, Email
from wtforms import ValidationError
from .models import User
from flask import flash
from wtforms.validators import Regexp

password = PasswordField('Password', validators=[DataRequired(), EqualTo('confirm_password'), Regexp(r'^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$', message="Password must be at least 8 characters long and contain letters and numbers.")])


class SignupForm(FlaskForm):
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    date_of_birth = DateField('Date of Birth', validators=[DataRequired()])
    phone_number = StringField('Phone Number', validators=[DataRequired()])
    email = EmailField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired(), EqualTo('confirm_password')])
    confirm_password = PasswordField('Confirm Password')
    submit = SubmitField('Create Account')

    
    # def check_email(self, field):
    #     if User.query.filter_by(email=field.data).first():
    #         raise ValidationError('This email address has already been registered!')
    # def check_username(self, field):
    #     if User.query.filter_by(username=field.data).first():
    #         raise ValidationError('This username is taken! Try another one!')

    
    
class LoginForm(FlaskForm):
    email = EmailField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')
    

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from config import Config
from flask_wtf.csrf import CSRFProtect


database = SQLAlchemy()
login_manager = LoginManager()

def create_app():
    app = Flask(__name__, template_folder='templates', static_folder='static')
    app.config.from_object(Config)
    csrf = CSRFProtect(app)

    database.init_app(app)
    Migrate(app, database)
    
    login_manager.init_app(app)
    login_manager.login_view = 'core.index'
    
    from app.routes import core
    app.register_blueprint(core)
    
    return app

app/routes.py
from flask import render_template, Blueprint, redirect, url_for, flash
from  .forms import SignupForm, LoginForm
from flask_login import login_required, current_user, logout_user, login_user
from .models import User
from app import database

core = Blueprint('core', __name__)

@core.route('/')
def index():
    return render_template('index.html')

@core.route('/signup_page', methods=['GET', 'POST'])
def signup():
    signup_form = SignupForm()
    
    if signup_form.validate_on_submit():
        user = User.query.filter_by(email=signup_form.email.data).first()
        # username = User.query.filter_by(username=signup_form.username.data).first()
        if user:
            flash('This email address has already been registered!', 'error')
            return redirect(url_for('core.signup'))
        # elif username:
        #     flash('This username is taken!, Try another one!')
        #     return redirect(url_for('core.signup'))

        
        new_user = User(
            first_name=signup_form.first_name.data,
            last_name=signup_form.last_name.data,
            date_of_birth=signup_form.date_of_birth.data,
            phone_number=signup_form.phone_number.data,
            email=signup_form.email.data,
            password=signup_form.password.data
        )
        database.session.add(new_user)
        database.session.commit()
        flash('Thanks for registering!')
        return redirect(url_for('core.dashboard'))
    elif signup_form.errors:
        flash('There are errors in your form. Please double check!', 'error')
    return render_template('signup_page.html', signup_form=signup_form)

@core.route('/login_page', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()
    if login_form.validate_on_submit():
        user = User.query.filter_by(email=login_form.email.data).first()
        if user and user.password == login_form.password.data:
            login_user(user)
            flash('Login successful!', 'success')
            return redirect(url_for('core.dashboard'))
        else:
            flash('Invalid email or password', 'error')
    return render_template('login_page.html', login_form=login_form)


@core.route('/dashboard')
@login_required
def dashboard():
    return render_template('dashboard.html', current_user=current_user)

@core.route('/logedout')
def logout():
    flash('You have been logged out', "info")
    logout_user()
    
    return render_template('index.html')

@core.route('/update-profile')
@login_required
def update_profile():
    return render_template('update_profile.html', current_user=current_user)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style/base.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='style/forms.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='style/dashboard.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='style/features.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='style/index.css') }}">
    <title>{% block page_title %}My Project{% endblock %}</title>

</head>

<body>
    <nav id="navbar">
        <ul id="navbar-ul-left">
            <li>My Project</li>
            <li><a href="{{url_for('core.index')}}">Home</a></li>
        </ul>
        {%block account_links%}
        <ul id="navbar-ul-right">
            <li><a href="{{ url_for('core.login') }}">Login</a></li>
            <li><a href="{{ url_for('core.signup') }}">Create Account</a></li>
        </ul>
        {%endblock%}
    </nav>

    <!-- Flash messages block -->
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="flashes">
        {% for category, message in messages %}
        <div class="flash {{ category }}">{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}
    {% endwith %}

    <section id="main-container">

        {% block header_container %}
        Header Container Test
        {% endblock %}

        {% block main_container %}
        Main Container Test
        {% endblock %}

        {% block extra_container %}
        Extra Container Test
        {% endblock %}
    </section>


    <footer>
        <div>Copyright Resered</div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{{ url_for('static', filename='javascript/index.js') }}"></script>
</body>

</html>

app/templates/dashboard.html
{% extends 'base.html'%}

{% block page_title %} Dashboard {% endblock %}

<!-- ====================Nav Bar Links ================-->
{% block account_links %}
<ul>
    <li id="user_image_icon-li">
        <img id="user_image_icon" src="{{ url_for('static', filename='assets/images/default_user_profile_img.jpg') }}"
            alt="User Image">
    </li>
    <li><a href="{{ url_for('core.logout') }}">Logout</a></li>
</ul>
{% endblock %}



<!-- ==================== Main Container ================-->
{% block header_container %}
<section class="main-container dashboard-container">

    <section class="dashboard-user-section">
        <div class="user-image-box">
            <img src="{{ url_for('static', filename='assets/images/default_user_profile_img.jpg') }}" alt="User Image">
        </div>

        <div class="user-info-container">
            <div class="user-info-header-box">
                <h1>Welcome, {{ current_user.first_name }}</h1>
                <p>Last login info</p>
            </div>
            <hr class="dashboard-header-hr">

            <div class="info-box-content-box">
                <div class="profile-details-container">
                    <div class="profile-detail">First Name: {{ current_user.first_name }}</div>
                    <div class="profile-detail">Last Name: {{ current_user.last_name }}</div>
                    <div class="profile-detail">Email: {{ current_user.email }}</div>
                    <div class="profile-detail">Phone: 123456789</div>
                </div>

                <div class="profile-details-buttons-box">
                    <button class="form-button edit-profile-button profile-buttons" onclick="window.location.href='{{ url_for('core.update_profile') }}'">Edit Profile</button>
                    <button class="form-button change-password-button profile-buttons" onclick="window.location.href='{{ url_for('core.update_password') }}'">Change Password</button>
                    <button class="form-button delete-account-button profile-buttons">Delete Account</button>
                </div>
            </div>


        </div>

    </section>
</section>

{%endblock%}

{% block main_container %}
<section class="dashboard-container">

    <section class="main-container features-section">

        <!-- FEATURE 1 - BUSINESS -->
        <div class="features-container">

            <div class="feature-header">
                <!-- flex row -->
                <h2>Business</h2>
                <p>Tools to manage your business</p>
            </div>
            <hr class="dashboard-header-hr">

            <div class="feature-body">
                <!-- inline block or flex row -->

                <button class="feature-body-content">
                    <!-- flex row -->
                    <img style="border-radius: 5px;" src="{{url_for('static', filename='assets/icons/vat-calculater-icon.png')}}">
                    <p>Calculate your VAT</p>
                </button>
                <button class="feature-body-content">
                    <!-- flex row -->
                    <img style="border-radius: 5px;" src="{{url_for('static', filename='assets/icons/invoice-issue-icon.png')}}">
                    <p>Issue Invoice</p>
                </button>
                <button class="feature-body-content">
                    <!-- flex row -->
                    <img style="border-radius: 5px;" src="{{url_for('static', filename='assets/icons/self-assessment-icon.png')}}">
                    <p>Self Assessment History</p>
                </button>
                <button class="feature-body-content">
                    <!-- flex row -->
                    <img style="border-radius: 5px;" src="{{url_for('static', filename='assets/icons/checklist-icon.png')}}">
                    <p>Your Scheduel</p>
                </button>
                <button class="feature-body-content">
                    <!-- flex row -->
                    <img style="border-radius: 5px;" src="{{url_for('static', filename='assets/icons/payslip-icon.jpg')}}">
                    <p>Your Payslips</p>
                </button>
            </div>
        </div>

        <!-- FEATURE 2 - EXTRA -->
        <div class="features-container">

            <div class="feature-header">
                <!-- flex row -->
                <h2>ُOther tools</h2>
                <p>Need a handy tool? you can find it hear.</p>
            </div>
            <hr class="dashboard-header-hr">

            <div class="feature-body">
                <!-- inline block or flex row -->
                <button class="feature-body-content">
                    <!-- flex row -->
                    <img src="{{url_for('static', filename='assets/icons/gpticon.png')}}">
                    <p>AI Agent</p>
                </button>
                <button class="feature-body-content">
                    <!-- flex row -->
                    <img style="border-radius: 5px;" src="{{url_for('static', filename='assets/icons/unit-converter-icon.jpeg')}}">
                    <p>Unit Converter</p>
                </button>
                <button class="feature-body-content">
                    <!-- flex row -->
                    <img style="border-radius: 50%;" src="{{url_for('static', filename='assets/icons/currency-converter-icon.jpeg')}}">
                    <p>Currency Converter</p>
                </button>
                <button class="feature-body-content">
                    <!-- flex row -->
                    <img style="border-radius: 5px;" src="{{url_for('static', filename='assets/icons/stock-icon.png')}}">
                    <p>Stock Price Tracking</p>
                </button>

            </div>
        </div>

        <!-- FEATURE 3 - INFORMATION -->
        <div class="features-container">

            <div class="feature-header">
                <!-- flex row -->
                <h2>Information</h2>
                <p>Here you can find information about HMRC, UTR, VAT Calculation and etc.</p>
            </div>
            <hr class="dashboard-header-hr">

            <div class="feature-body">
                <!-- inline block or flex row -->

                <button class="feature-body-content">
                    <!-- flex row -->
                    <img style="border-radius: 5px;" src="{{url_for('static', filename='assets/icons/uc-icon.jpg')}}">
                    <p>Universal Credit</p>
                </button>
                <button class="feature-body-content">
                    <!-- flex row -->
                    <img style="border-radius: 5px;" src="{{url_for('static', filename='assets/icons/hmrc-icon.png')}}">
                    <p>HMRC</p>
                </button>
                <button class="feature-body-content">
                    <!-- flex row -->
                    <img style="border-radius: 5px;" src="{{url_for('static', filename='assets/icons/dvla-icon.png')}}">
                    <p>Driving Licence </p>
                </button>
                <button class="feature-body-content">
                    <!-- flex row -->
                    <img style="border-radius: 5px;" src="{{url_for('static', filename='assets/icons/selfemployement-icon.png')}}">
                    <p>Self Employment</p>
                </button>
                <button class="feature-body-content">
                    <!-- flex row -->
                    <img style="border-radius: 5px;" src="{{url_for('static', filename='assets/icons/self-assessment-icon2.png')}}">
                    <p>Self Assessment</p>
                </button>

            </div>
        </div>
    </section>
</section>
{% endblock %}

app/templates/index.html
<!DOCTYPE html>
{% extends 'base.html'%}

{% block page_title %} My Project {% endblock %}

{% block header_container %}

<section class="main-header-container">
<h1>WELCOME to Personal Assistant Project</h1>
<p class="mp-header-description">
    This is a personal assistant project that helps you manage your tasks and schedule efficiently. 
    It is designed to be user-friendly and intuitive, making it easy for you to stay organized and productive.    
</p>
<button class="mp-primary-button">Click Me</button>
<div class="mp-features-container">
    <div class="mp-feature">
        <img src="{{url_for('static', filename='assets/icons/financing.jpeg')}}" alt="Feature 1">
    </div>
    <div class="mp-feature">
        <img src="{{url_for('static', filename='assets/icons/personal-management.jpeg')}}" alt="Feature 2">
    </div>
    <div class="mp-feature">
        <img src="{{url_for('static', filename='assets/icons/learning.jpeg')}}" alt="Feature 3">
    </div>
</div>
</section>

{% endblock %}

{% block main_container %}
Main Container Test - INDEX
{% endblock %}

{% block extra_container %}
Extra Container Test - INDEX
{% endblock %}

app/templates/login_page.html
{% extends 'base.html'%}

{% block page_title %} Log In {% endblock %}

{% block main_container %}
<div class="form-frame">
    <form class="profile-form" method="POST" action="{{ url_for('core.login') }}">
        {{ login_form.hidden_tag() }}

        <h2>Log In</h2>

        {{login_form.email.label(class="form-label")}}
        {{login_form.email(class="form-input")}}

        {{login_form.password.label(class="form-label")}}
        {{login_form.password(class="form-input")}}

        {{login_form.submit(class="form-button")}}
    </form>
</div>


{% endblock %}

app/templates/signup_page.html
{% extends 'base.html'%}

{% block page_title %} Create Account {% endblock %}

{% block main_container %}
<div class="form-frame">
    <form class="profile-form" method="POST" action="{{ url_for('core.signup') }}">
        {{signup_form.hidden_tag()}}

        <h2>Create Account</h2>

        {{signup_form.first_name.label(class="form-label", id="first_name-label")}}
        {{signup_form.first_name(class="form-input", id="first_name-input")}}

        {{signup_form.last_name.label(class="form-label", id="last_name-label")}}
        {{signup_form.last_name(class="form-input", id="last_name-input")}}

        {{signup_form.date_of_birth.label(class="form-label", id="date_of_birth-label")}}
        {{signup_form.date_of_birth(class="form-input", id="date_of_birth-input")}}
        <br>
        {{signup_form.phone_number.label(class="form-label", id="phone_number-label")}}
        {{signup_form.phone_number(class="form-input", id="phone_number-input")}}

        {{signup_form.email.label(class="form-label", id="email-label")}}
        {{signup_form.email(class="form-input", id="email-input")}}

        {{signup_form.password.label(class="form-label", id="password-label")}}
        {{signup_form.password(class="form-input", id="password-input")}}

        {{signup_form.confirm_password.label(class="form-label", id="confirm_password-label")}}
        {{signup_form.confirm_password(class="form-input", id="confirm_password-input")}}

        <div id="password-confirmation-match">
            <ul>
                <li id="password-confirmation-match">Your passwords do not match</li>
            </ul>
        </div>

        <div id="password-validation-list">
            <ul>
                <li id="password-validation-list-item-1">At least 8 characters long</li>
                <li id="password-validation-list-item-2">Contain at least one uppercase letter</li>
                <li id="password-validation-list-item-3">Contain at least one lowercase letter</li>
                <li id="password-validation-list-item-4">Contain at least one number</li>
                <li id="password-validation-list-item-5">Contain at least one special character</li>
            </ul>
        </div>


        {{signup_form.submit(class="form-button", id="registeration-submit-button")}}
    </form>
</div>


{% endblock %}

app/templates/update_password.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block page_title %} Update Profile {% endblock %}

{% block account_links %}
<ul>
    <li id="user_image_icon-li">
        <img id="user_image_icon" src="{{ url_for('static', filename='assets/images/default_user_profile_img.jpg') }}"
            alt="User Image">
    </li>
    <li><a href="{{ url_for('core.logout') }}">Logout</a></li>
</ul>
{% endblock %}

{% block header_container %}
{%endblock%}

{% block main_container %}
Test
{% endblock %}

app/templates/update_profile.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block page_title %} Update Profile {% endblock %}

{% block account_links %}
<ul>
    <li id="user_image_icon-li">
        <img id="user_image_icon" src="{{ url_for('static', filename='assets/images/default_user_profile_img.jpg') }}"
            alt="User Image">
    </li>
    <li><a href="{{ url_for('core.logout') }}">Logout</a></li>
</ul>
{% endblock %}

{% block header_container %}
{%endblock%}

{% block main_container %}
Test
{% endblock %}